modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="Apache License 2.0"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId="spacecraft" #mandatory
version="${file.jarVersion}" #mandatory
displayName="SpaceCraft" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="examplemod.png" #optional
credits="Mojang for making the Minecraft. Forge for making Forge. Brian Cox for making programs about space." #optional
authors="JamesDaProgrammer A.K.A James Hamilton" #optional
description='''
SpaceCraft is currently a Minecraft mod which does absolutely nothing :)
'''

[[dependencies.spacecraft]] #optional
        modId="forge" #mandatory
        mandatory=true #mandatory
        versionRange="[40,)" #mandatory
        ordering="NONE"
        side="BOTH"
[[dependencies.spacecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
